/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out and revoke the session */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["read_current_user_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account and sign in */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every available filter value */
        get: operations["read_catalog_api_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/missed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Questions answered incorrectly at least once */
        get: operations["read_missed_questions_api_progress_missed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weakest subjects, least accurate first */
        get: operations["read_weakest_subjects_api_progress_subjects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Accuracy by domain */
        get: operations["read_summary_api_progress_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse questions */
        get: operations["list_questions_api_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one question */
        get: operations["read_question_api_questions__question_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-guide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Weak areas and the concepts behind every missed question
         * @description Empty focus areas mean nothing has been answered incorrectly yet.
         */
        get: operations["read_review_guide_api_review_guide_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        /** Start a study session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a session */
        get: operations["read_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit an answer and receive the explanation */
        post: operations["submit_answer_api_sessions__session_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/current-question": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The question awaiting an answer */
        get: operations["read_current_question_api_sessions__session_id__current_question_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End a session early */
        post: operations["end_session_api_sessions__session_id__end_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** How the session went */
        get: operations["read_session_summary_api_sessions__session_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Report that the process is running. Deliberately does not touch the database.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Report whether dependencies are available, so orchestrators can delay traffic.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnswerRequest
         * @description A displayed letter, or null to skip the question.
         */
        AnswerRequest: {
            /** Choice */
            choice?: ("a" | "b" | "c" | "d") | null;
        };
        /** AnswerResponse */
        AnswerResponse: {
            /** Correct Choice */
            correct_choice: string;
            /** Correct Choice Text */
            correct_choice_text: string;
            /** Correction Note */
            correction_note: string | null;
            /** Explanation */
            explanation: string;
            /** Next Available */
            next_available: boolean;
            /** Position */
            position: number;
            result: components["schemas"]["AttemptResult"];
            /** Session Status */
            session_status: string;
            /** Total */
            total: number;
        };
        /**
         * AttemptResult
         * @enum {string}
         */
        AttemptResult: "correct" | "incorrect" | "skipped";
        /**
         * CatalogResponse
         * @description Every value that can be used to filter a study session.
         */
        CatalogResponse: {
            /** Chapters */
            chapters: string[];
            /** Domains */
            domains: string[];
            /** Objectives */
            objectives: string[];
            /** Question Count */
            question_count: number;
            /** Subjects */
            subjects: string[];
        };
        /** DomainPriority */
        DomainPriority: {
            /** Accuracy */
            accuracy: number;
            /** Domain */
            domain: string;
            /** Incorrect */
            incorrect: number;
            /** Rank */
            rank: number;
            /** Weakness Score */
            weakness_score: number;
        };
        /** FocusArea */
        FocusArea: {
            /** Accuracy */
            accuracy: number;
            /** Concepts */
            concepts?: components["schemas"]["ReviewConcept"][];
            /** Correct */
            correct: number;
            /** Domain */
            domain: string;
            /** Incorrect */
            incorrect: number;
            /** Rank */
            rank: number;
            /** Subject */
            subject: string;
            /** Weakness Score */
            weakness_score: number;
        };
        /** GroupStatsResponse */
        GroupStatsResponse: {
            /** Accuracy */
            accuracy: number;
            /** Attempts */
            attempts: number;
            /** Correct */
            correct: number;
            /** Graded */
            graded: number;
            /** Incorrect */
            incorrect: number;
            /** Name */
            name: string;
            /** Skipped */
            skipped: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** MissedQuestionSet */
        MissedQuestionSet: {
            /** Count */
            count: number;
            /** Question Ids */
            question_ids: string[];
        };
        /** MissedQuestionsResponse */
        MissedQuestionsResponse: {
            all: components["schemas"]["MissedQuestionSet"];
            unresolved: components["schemas"]["MissedQuestionSet"];
        };
        /**
         * MissedScope
         * @enum {string}
         */
        MissedScope: "all" | "unresolved";
        /** ProgressSummaryResponse */
        ProgressSummaryResponse: {
            /** Accuracy */
            accuracy: number;
            /** Attempts */
            attempts: number;
            /** Correct */
            correct: number;
            /** Domains */
            domains: components["schemas"]["GroupStatsResponse"][];
            /** Graded */
            graded: number;
            /** Incorrect */
            incorrect: number;
            /** Skipped */
            skipped: number;
        };
        /** QuestionPage */
        QuestionPage: {
            /** Items */
            items: components["schemas"]["QuestionSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * QuestionSummary
         * @description A question as sent to an unauthenticated client.
         *
         *     The answer, explanation, and correction note are deliberately omitted; they are revealed
         *     only in the response to a submitted answer.
         */
        QuestionSummary: {
            /** Chapter */
            chapter: string;
            /** Choices */
            choices: {
                [key: string]: string;
            };
            /** Domain */
            domain: string;
            /** Id */
            id: string;
            /** Objective */
            objective: string;
            /** Question */
            question: string;
            /** Subject */
            subject: string;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Database */
            database: string;
            /** Status */
            status: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** ReviewConcept */
        ReviewConcept: {
            /** Chapter */
            chapter: string;
            /** Correct Choice */
            correct_choice: string;
            /** Correction Note */
            correction_note?: string | null;
            /** Explanation */
            explanation: string;
            /** Objective */
            objective: string;
            /** Prompt */
            prompt: string;
            /** Question Id */
            question_id: string;
        };
        /** ReviewGuide */
        ReviewGuide: {
            /** Focus Areas */
            focus_areas?: components["schemas"]["FocusArea"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Overall Accuracy */
            overall_accuracy: number;
            /** Priority Domains */
            priority_domains?: components["schemas"]["DomainPriority"][];
            /** Total Correct */
            total_correct: number;
            /** Total Graded */
            total_graded: number;
            /** Total Incorrect */
            total_incorrect: number;
        };
        /** SessionCreateRequest */
        SessionCreateRequest: {
            /** Count */
            count?: number | null;
            /** Filter Value */
            filter_value?: string | null;
            /** @default all */
            missed_scope: components["schemas"]["MissedScope"];
            mode: components["schemas"]["StudyMode"];
            /**
             * Shuffle Answers
             * @default false
             */
            shuffle_answers: boolean;
            /**
             * Shuffle Questions
             * @default true
             */
            shuffle_questions: boolean;
        };
        /** SessionQuestionResponse */
        SessionQuestionResponse: {
            /** Position */
            position: number;
            question: components["schemas"]["QuestionSummary"];
            /** Total */
            total: number;
        };
        /** SessionSummaryResponse */
        SessionSummaryResponse: {
            /** Accuracy */
            accuracy: number;
            /** Answered */
            answered: number;
            /** Correct */
            correct: number;
            /** Incorrect */
            incorrect: number;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Skipped */
            skipped: number;
            /** Status */
            status: string;
            /** Total Questions */
            total_questions: number;
        };
        /**
         * StudyMode
         * @enum {string}
         */
        StudyMode: "all" | "domain" | "chapter" | "subject" | "objective" | "missed" | "practice";
        /** StudySessionResponse */
        StudySessionResponse: {
            /** Answered */
            answered: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Filters */
            filters: {
                [key: string]: string;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Mode */
            mode: string;
            /** Shuffle Answers */
            shuffle_answers: boolean;
            /** Status */
            status: string;
            /** Total Questions */
            total_questions: number;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Echo the value of the sp_csrf cookie. */
                "x-csrf-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_current_user_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_catalog_api_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogResponse"];
                };
            };
        };
    };
    read_missed_questions_api_progress_missed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissedQuestionsResponse"];
                };
            };
        };
    };
    read_weakest_subjects_api_progress_subjects_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupStatsResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_summary_api_progress_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressSummaryResponse"];
                };
            };
        };
    };
    list_questions_api_questions_get: {
        parameters: {
            query?: {
                domain?: string | null;
                chapter?: string | null;
                subject?: string | null;
                objective?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_question_api_questions__question_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_review_guide_api_review_guide_get: {
        parameters: {
            query?: {
                max_focus_areas?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewGuide"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudySessionResponse"][];
                };
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Echo the value of the sp_csrf cookie. */
                "x-csrf-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudySessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudySessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_answer_api_sessions__session_id__answer_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Echo the value of the sp_csrf cookie. */
                "x-csrf-token"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_current_question_api_sessions__session_id__current_question_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionQuestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_session_api_sessions__session_id__end_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Echo the value of the sp_csrf cookie. */
                "x-csrf-token"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudySessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_session_summary_api_sessions__session_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
}
